### ISSUE TITLE
"11 Things I Hate About U" path reward has the wrong name

### ISSUE THREAD

**Issue by txster** [m-e-meyer/av-snapshot#10]
Instead of 'Thwaitgold Illinigina illinoiensis statuette' to follow the usual pattern, the reward is the 'Thwaitgold Illinigina illinoiensis model' to make sure it has no U in it :)

(Not 100% sure of the data file format regarding whitespace so raising this as an issue instead of a PR sowwy!)

**Comment by m-e-meyer** [comment]
Sorry for the delay, but I did see your message... Fixed!  Thanks for the heads-up!

**Comment by m-e-meyer** [comment]
Forgot to close :-)
