### ISSUE TITLE
Tattoo outfits have misnamed items.

### ISSUE THREAD

**Issue by MattiasKro** [m-e-meyer/av-snapshot#13]
Some of the items in tattoos are misspelled or have changed names during the years
The following should be corrected in av-snapshot- tattoos.txt:

- coloured-light "necklace" -> colored-light "necklace"
- floaty prock pants -> floaty rock pants
- homoerotic frat-paddle -> orcish frat-paddle
- 7-fot dwarven mattock -> 7-foot dwarwen mattock
- time pants -> time trousers
- tropical crimbo pants -> tropical crimbo shorts

**Comment by m-e-meyer** [comment]
Changes adopted.  Thanks!
