### ISSUE TITLE
Depleted grimacite hammer in DC but not in snapshot.

### ISSUE THREAD

**Issue by djve60** [m-e-meyer/av-snapshot#3]
https://api.aventuristo.net/av-snapshot?u=beljeferon shows the hammer as not being done, but I'm sure it is.

Is there anyway to fix this anomaly?

**Comment by m-e-meyer** [comment]
Did you try the suggestion, "Turn Inventory Images ON and one-click crafting OFF and try again - it has a higher success rate."  That's a holdover from Cheesecookie's snapshots; I've never tried it myself.  The other thing to try is manually looking in the Discoveries section of Crafting and confirming Beljeferon does know the recipe for depleted Grimacite hammers.

**Comment by djve60** [comment]
I forgot about the "tun inventory images off.. etc.". The account is in run, but as soon as it's finished I'll try again.

Also the person that owns the account seems to have told me things that were not true. The account doesn't show it knows the recipe for depleted grimacite hammers. However it does show it know the Crimbo duds recipes, and they are not showing.

However, give me 4 days to get it out of the current HC challenge path and report back. 

Thanks for the kick on the inventory, and crafting, and the excellent work on av-snapshot.

**Comment by djve60** [comment]
Looks like the owner of Beljeferon is smoking crack. All the items that he complained about are also missing from https://cheesellc.com/kol/profile.php?u=Beljeferon, and they are tradable items. So I believe I've wasted your time.

My most humble apologies.

David
