### ISSUE TITLE
99.44% pure math link doesn't seem to be handling % sign appropriately

### ISSUE THREAD

**Issue by dizzydis** [m-e-meyer/av-snapshot#4]
The Wiki Link for 99.44% pure math is breaking as I don't believe its correctly handling the $ character when buildling the link.

Using Chrome.
Copy Link Address on snapshot page gives me: 
`http://kol.coldfront.net/thekolwiki/index.php/99.44%%20pure%20math`

Copy Link Address from google gives me: 
`https://kol.coldfront.net/thekolwiki/index.php/99.44%25_pure_math`

The result is I get taken to a 400.shtml page

**Comment by m-e-meyer** [comment]
Yep, that's a bug, thanks.  I'll get to it this weekend, when my family's out of town. :-)

**Comment by m-e-meyer** [comment]
Fixed with commit [898c223](https://github.com/m-e-meyer/av-snapshot/commit/898c223a1a7cdd0ede06cc1287555f85d2867724)

**Comment by dizzydis** [comment]
You rock! Thanks
