### ISSUE TITLE
Minor issues when using "name change" form.

### ISSUE THREAD

**Issue by djve60** [m-e-meyer/av-snapshot#5]
Minor issue. I just changed account names and the snapshot was pretty good at updating "most" things.

So far I see it missed the following ItoMs which are in use and I'm not rich enough to have spares in the DC:
1. Chateau Mantegna room key -> The Big Mountains -> Chateau Mantegna
2. X-32-Fsnowman crate -> The Big Mountains ->The Snojo
3. LT&T telegraph office deed -> right side of the tracks -> LT&T Office
4. detective school application -> wrong side of the tracks -> 11th Precinct Headquarters
5. hear-shaped create -> wrong side of the tracks -> Tunnel of L.O.V.E.

See the snapshots for "djve" (original) and "de nisovan" (new name).

If these need to be set manually, you may want to add the instruction.

Feel free to close this as won't fix as it may be too hard to fix.

**Comment by m-e-meyer** [comment]
@djve60 , maybe they _do_ need to be set manually.  Check out the FAQ I've just added to README.md in the dev branch.  Are those properties unset for you?

**Comment by djve60** [comment]
I did try turning images off, logging out, reloading. None of that worked.

However all items are now recognized. I did this by:
1. CM: used the desk (for potions) and rerun the snapshot and it was recognized.
2. LT&T: started a daily quest, then rerun the snapshot and it was recognized.
3. Detective school application: ran the daily quest, then rerun the snapshot and it was NOT recognized. Purchased an item from the store then rerun the snapshot and it was recognized.
4. Ran the 3 combats and ran the snapshot before making a selection for the final item, and it was recognized.

Thanks,

D

**Comment by m-e-meyer** [comment]
Aw... you didn't check out your values of the properties listed in my development branch's README.md?  :-(  That's how I was intending to address your issue.  Obviously, av-snapshot can't start an LT&T quest just to set a property. :-)

**Comment by djve60** [comment]
I don't go into the development branch, unless asked to. But as I said, minor issue.

And here's another minor issue, that I don't understand. If you look at the profile of "play4smee" in game you'll see they have an HP permed skill "[8.placeholder]".  Any idea what's that about? Probably not, as it doesn't seem to do anything.

**Comment by m-e-meyer** [comment]
play4smee no longer has a skill "[8.placeholder]", so closing as OBE.

**Comment by m-e-meyer** [comment]
Trying again to close :-)
