### ISSUE TITLE
mafia r27496 now has a property to track Florist Friar ownership

### ISSUE THREAD

**Issue by Rinn** [m-e-meyer/av-snapshot#6]
As of [r27496](https://github.com/kolmafia/kolmafia/releases/tag/r27496) you can now check the `ownsFloristFriar` property and that will denote if the account owns it even if the forest is currently inaccessible this ascension.

**Comment by m-e-meyer** [comment]
@Rinn , thanks, I've made the change in my environment.  Should I use `since` to enforce r27496?

**Comment by Rinn** [comment]
there's no breaking change regarding this in that revision, the prop just won't exist

**Comment by m-e-meyer** [comment]
Okay, I won't enforce it then.  Thanks for the advice
