### ISSUE TITLE
Caveman Dan's favorite rock URL incorrect

### ISSUE THREAD

**Issue by dizzydis** [m-e-meyer/av-snapshot#7]
AV Snapshot updated this morning.

The Caveman Dan's rock URL takes me to:
`https://kol.coldfront.net/thekolwiki/index.php/Caveman_Dan%27s_Favorite_Rock`

This leads to a non-existent wiki entry as the correct URL is:
`https://kol.coldfront.net/thekolwiki/index.php/Caveman_Dan%27s_favorite_rock`

The 'f' and 'r' in 'favorite rock' need to be lowercase

**Comment by m-e-meyer** [comment]
Thanks!  Should be fixed now.
