### ISSUE TITLE
chest mimic not detected

### ISSUE THREAD

**Issue by alch-1** [m-e-meyer/av-snapshot#8]
I have a chest mimic but av-snapshot doesn't detect it. 

Not a big deal but posting here in case it can be fixed. thanks

**Comment by m-e-meyer** [comment]
To diagnose this problem I'm going to need at least _some_ information.  What's your in-game name?  Have you tried again recently?

**Comment by alch-1** [comment]
sure. i am PhaZer (#1813527) in game, you can find my snapshot here: https://api.aventuristo.net/av-snapshot?u=phazer#a4

as you can see, i have the chest mimic. i last ran it again today but it still doesn't show up. 
![photo_2024-01-15_13-02-49](https://github.com/m-e-meyer/av-snapshot/assets/40395541/b0764474-4067-4337-a019-e5b8a49e25f9)

**Comment by alch-1** [comment]
i see you pushed a fix, thanks! it works now. closing.
